# Generated by Django 4.2 on 2025-01-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_cart_identifier_cart_updated_at_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
