# Generated by Django 5.1.4 on 2025-01-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.variant'),
        ),
    ]
