# Generated by Django 5.1.4 on 2025-01-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_value_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
