# Generated by Django 5.1.4 on 2025-01-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_category_name'),
        ('ecomapp', '0008_alter_variant_sku'),
    ]

    operations = [
    ]
