# Generated by Django 5.1.4 on 2025-01-16 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_baseuser_options_alter_customers_options_and_more'),
        ('ecomapp', '0009_merge_0008_alter_category_name_0008_alter_variant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounts.vendors'),
        ),
    ]
