# Generated by Django 5.1.4 on 2025-01-17 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_review_options_review_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='reply',
            unique_together={('review', 'user')},
        ),
    ]
