# Generated by Django 5.1.4 on 2025-01-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_remove_customer_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendors',
        ),
    ]
