# Generated by Django 4.2 on 2025-01-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_variant_sku'),
        ('orders', '0002_remove_order_updated_at_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.variant'),
            preserve_default=False,
        ),
    ]
