# Generated by Django 4.2 on 2025-01-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
